### PR TITLE
Implementation jiraDownloadAttachment & jiraAttachFile

### PR DESCRIPTION
**Pull request by OBreitenbach**
I implemented two new steps: 

- jiraDownloadAttachment

- jiraAttachFile

The user is now allowed to attach a file to an issue or download an attachment from an issue.
I also added unit tests for these steps and wrote some javadoc.

### CODE REVIEW

**Comment by nrayapati** [comment]
@OBreitenbach  I am curious, what is your use case around these steps? just wanted to further understand. Thanks.

**Comment by OBreitenbach** [comment]
@nrayapati We need the ability to upload documents (e.g. screenshots, Excel sheets, etc.) to JIRA tickets or act on specific documents that are attached to the tickets in some Jenkins pipelines. So the upload and download is quite essential and wasn't available so far. The jiraListAttachments is a short-hand function to easily receive the list of attachments as opposed to retrieving the full ticket info along with all data. Before extending this nice plugin, we had to rely on complicated shell scripts. Please ask, if you have any further questions or refactoring wishes.

**Comment by colourmeamused** [comment]
I would definitely in favour of these changes being included, and any of the 'core' [automation-friendly API calls](https://docs.atlassian.com/jira/REST/server/).
Just one use case is uploading screenshots, logs etc. when a Jira is created automatically for a failed project build.
I definitely like the idea behind this plugin - a clean start and atomic pipeline steps with minimum global configuration.
A major issue with having so many Jira plugins is they only provide a subset of functionality.
Would you be looking to add maintainers?
Also is there a compatibility list for Jira versions this plugin works with, both Cloud and Server?

**Comment by zainaloha** [comment]
I too came to a scenario where I need to attach the test report from selenium to be included when reporting the issue. This update would help a lot of devops/qa automation engineers. Great plugin by the way.

**Comment by nrayapati** [comment]
@OBreitenbach Sorry for the late response, being busy with other things couldn't respond here.

Understand the use case of download and update documents to a JIRA issue, but I was wondering on how are you planning to get files on to the jenkins node before you run this pipeline to upload one, or how are you planning to make use of the files those are being downloaded from the pipeline?

While back, I have started drafted something on these steps but couldn't complete those yet :( , but which is to upload and download documents to/from workspace so that we can commit/read those files from scm like github. or it could be any source somehow those are files are available in the workspace rather than a random location on the node. 

If this is your use case I would like to finish my changes in and put that out here so that you guys can comment. Any thoughts?

**Comment by nrayapati** [comment]
@colourmeamused Appreciate your comment, exactly goal here is to provide more generic steps, so that users can combine those based on their use case. Contributions are welcome. I would be happy if you can contribute by following some notes [here.](https://jenkinsci.github.io/jira-steps-plugin/contributing.html)  

And this plugin should support any version regardless of whether it is cloud or a server as soon as the REST api stays the same.

**Comment by nrayapati** [comment]
Thanks @zainaloha, hopefully soon we will have few steps around this functionality. :)

**Comment by marbon87** [comment]
Any change that this will be corrected and merge soon? I need these functions  :+1:

**Comment by nrayapati** [comment]
@marbon87  I will have these steps go into master soon, but probably with the code that I have already.

**Comment by roshnij7** [comment]
May I know when the feature will be released.

**Comment by nrayapati** [comment]
@OBreitenbach I have opened another pull request with more changes in case if you wanted to take are look at it. #64

**Comment by nrayapati** [comment]
Closing this one, as I have merged the other one #64, Will release it after further testing.

**Pull request closed without merging**
