### PR TITLE
JENKINS-62193: Proxy Support : Missing no-proxy host management

### PR DESCRIPTION
**Pull request by flocard**
# Description

See [JENKINS-62193] (https://issues.jenkins-ci.org/browse/JENKINS-62193).

# Manual tests instructions:
- Configure a proxy in Jenkins settings for outside communication ( Jenkins - Manage Jenkins - Manage Plugins Advanced).
- UseCase 1 : jira must be accessed through the proxy : jira host is not in "noproxy host list" config
- UseCase 2 : jira access is direct : jira host is in "proxy hostlist" config

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description.
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests.
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description.
- [ ] Reviewed the code.
- [ ] Verified that the appropriate tests have been written or valid explanation given.
- [ ] If applicable, tested by installing this plugin on the Jenkins instance.

### CODE REVIEW

**Comment by guija** [comment]
Hi @flocard . Thanks a lot for the fast fix. @nrayapati could you please have a look at this as we have a lot of pipelines that are relying on this feature. It would be nice if a release could be created soon. Thanks a lot.

**Comment by nrayapati** [comment]
Thanks a bunch @flocard  for quick changes, changes looks good to me. 

@guija Would you be able to help test this change quickly by installing snapshot please so that I can get this released today some time

**Comment by guija** [comment]
Thanks for the hint @nrayapati . Thats very conveniant. I can confirm that it works with our setup:
- Jenkins and Jira are in the same internal network
- Proxy configured over Jira Plugin Settings
- "No Proxy" configured over Jira Plugin Settings.
- With Testing functionality of Jira Steps plugin in the "Configure System" settings it now works (It didn't work before).

**Comment by nrayapati** [comment]
@guija Awesome! thank you for the confirmation.

**Comment by nrayapati** [comment]
Released 1.5.5, it should be available in update center soon. Thank you @flocard  and @guija for all your help! Really appreciate it.

**Comment by nrayapati** [comment]
Just in case if any wants to install it manually: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/jira-steps/1.5.5/

**Comment by guija** [comment]
Pefect, thanks a lot @nrayapati

**Comment by guija** [comment]
@nrayapati I think release notes have to be still updated: https://jenkinsci.github.io/jira-steps-plugin/changelog/

**Comment by nrayapati** [comment]
Thank you @guija Published it.

**Pull request merged**
