### PR TITLE
Update JiraEndPoints.java

### PR DESCRIPTION
**Pull request by tapvirvirk**

### CODE REVIEW

**Comment by tapvirvirk** [comment]
@nrayapati Can you please review the PR?

Thanks
Tapvir

**Comment by nrayapati** [comment]
@tapvirvirk is this causing any failures with attachments steps? I did verify that those steps are working fine though.

**Comment by tapvirvirk** [comment]
@nrayapati - Yes it is giving error with 404. The reason for that is that in the JIRA configuration under configure system, '/' is required in the url at the end otherwise it is giving error on the configuration page.
And we have also '/' in the REST method which is causing the problem.

**Comment by nrayapati** [comment]
@tapvirvirk / at the end is not mandatory for global config, it is being sanitized automatically, I couldn't reproduce the issue that are reporting. Would you mind providing the more information like a pipeline code and error message that you see. 

And from the retrofit documents the extra slash in front the path url is not a problem.

**Comment by tapvirvirk** [comment]
@nrayapati 
In the above snapshot, If I remove the last '/' then it gives an error
jira_configuration_1

**Comment by nrayapati** [comment]
Can you also post the `Error Message:` , which usually prints after `Error Code:`? 

As I said before the extra `/` in front of the path shouldn't be an issue, I have tested it locally, but only difference that I see here is extra `/jira/` at the end, not sure if that is causing any problem. 

I found another issue with these steps in the morning and I have released 1.4.1 with the fix along side I have also removed these slashes, the new version should be available soon, usually it takes 3-4 hrs show up on the update center after release.

**Comment by nrayapati** [comment]
@tapvirvirk  I have tested following example, which is working properly, with 1.4.0, this wasn't working on the slaves, try to test it with the latest version may be. 
```groovy
node {
    writeFile file: 'test.txt', text: 'Test Attachment - Hello'

    def attachment = jiraUploadAttachment idOrKey: 'TEST-123', file: 'test.txt', site: 'JIRA'
    def attachmentId = attachment.data[0].id.toString()

    attachment = jiraGetAttachmentInfo id: attachmentId, site: 'JIRA'
    echo attachment.data.toString()

    jiraDownloadAttachment id: attachmentId, file: "test.txt", override: true, site: 'JIRA'
    def file = readFile 'test.txt'
    echo file.toString()

    jiraDeleteAttachment id: attachmentId, site: 'JIRA'
}
```

**Comment by tapvirvirk** [comment]
@nrayapati 
I see that you have removed the '/' from the java file which was the reason to open the current PR.
I think, we can close this PR as this will be fixed in 1.4.1 release.
I will test the new version once it is available in update center.

Thanks
Tapvir

**Comment by nrayapati** [comment]
@tapvirvirk Thanks for your help reporting this issue, 1.4.1 is available now, let me know if you need more help with it. 

Thanks again.

**Comment by tapvirvirk** [comment]
@nrayapati 
I tested the 1.4.1 on my local, it is working fine now.

Thanks for making the change.

**Comment by nrayapati** [comment]
Awesome @tapvirvirk

**Comment by tapvirvirk** [comment]
@nrayapati 
One question, when the jira is created, it adds the description with 
{panel}Automatically created by: [~virkt] from [Build URL|https://xxx.com/job/Jenkins_JIRA_Integration/94/]{panel}

Any way if I can remove this text?

**Comment by tapvirvirk** [comment]
@nrayapati 
I think I found a way to ignore it using auditLog parameter

**Pull request closed without merging**
