### PR TITLE
:sparkles: Changed the username for accountId for GDPR changes

### PR DESCRIPTION
**Pull request by mauriciojovel**
Added support to set the assignee with the accountId, only change the parameter in the jira function body

### CODE REVIEW

**Comment by ryparker** [comment]
Hey there I randomly came across this issue with the same problem. However I thought i'd share my solution. 

I've found the following to work with Jira's edit issue API:
`{"assignee": [{"set": {"id": accountId}}]}`

**Comment by nrayapati** [comment]
@mauriciojovel I am curious, is this a non-passive change to the existing JIRA API, or is this an extra field that is only available for JIRA hosted in EU regions? This change would break existing JIRA servers. 

When I look at this api on the latest server there is no reference of this accountId
https://docs.atlassian.com/software/jira/docs/api/REST/8.8.1/#api/2/issue-assign

**Comment by vadru** [comment]
> @mauriciojovel I am curious, is this a non-passive change to the existing JIRA API, or is this an extra field that is only available for JIRA hosted in EU regions? This change would break existing JIRA servers.
> 
> When I look at this api on the latest server there is no reference of this accountId
> https://docs.atlassian.com/software/jira/docs/api/REST/8.8.1/#api/2/issue-assign

I'm using cloud. For standalone solution and old installations maybe is better to have extrafield accountId in order to supply one or other depending upon jira version

**Comment by terk28041** [comment]
Hi everybody
Maybe I write it there but I haven’t found another place
I have a problem with this plugin
After installing on Jenkins version 2.222.1, it is in the docker container
The plugin when trying to connect to the jira will display an error "connect timed out"

**Comment by nrayapati** [comment]
@terk28041 you can log a JIRA as mentioned here https://github.com/jenkinsci/jira-steps-plugin#disclaimer

And for the connect timeout error, it is basically either container doesn't have access to the JIRA server that you are trying to connect or actual JIRA server is taking longer time than what is configured for this JIRA site in Jenkins configure page.

**Comment by terk28041** [comment]
In fact, it is interesting that another plug-in for the jira from the same Jenkins gets access.
And from the container with the help of curls you get to reach the jira
I beg you to help me since we really need a plug-in without the work of teams it will not be possible.

**Comment by nrayapati** [comment]
> In fact, it is interesting that another plug-in for the jira from the same Jenkins gets access.
> And from the container with the help of curls you get to reach the jira
> I beg you to help me since we really need a plug-in without the work of teams it will not be possible.
> We also use your plugin on another Jenkins, but there the version of Jenkins is 2.127 and on this version everything works with standard parameters and without a container.
> On the new I use 2.222.1 in the container

As mentioned before try to increase the connection timeout settings in global config page and see that helps. 

JIRA Sites configure

**Comment by terk28041** [comment]
@nrayapati 
Unfortunately, increasing the wait time did not help (((
I tried with 60,000 ms also did not help.
And tell me, maybe the plugin uses some specific ports, or how does it get to the jira?
Annotation 2020-04-28 182136

**Comment by nrayapati** [comment]
It doesn't use any specific ports and so on, if it is working on other Jenkins with same settings it should work on any Jenkins on the same network unless there are some restrictions or issues around the network. 

Not sure if you need to setup a proxy in docker container to get to the actual internet, in that case this plugin doesn't support that yet, we merged that change to master but not released yet.

**Comment by nrayapati** [comment]
@mauriciojovel sorry to spam this PR, @terk28041 would you be able to log a JIRA and we can have this discussion on it instead of another PR please

**Comment by terk28041** [comment]
Yes, I use a proxy inside the container and if you say that the plug-in does not cut it yet, then I will wait for the release of the new version)
And when is it about to wait for the new version ??
Thank you very much for your help)
If you need any help with testing the plugin with a proxy in the container, I am ready to help you.
It’s just that we are very dependent on your plugin and cannot use anything else; it just doesn’t suit us.

**Comment by terk28041** [comment]
And yes, I'm sorry that spam is here ((
It’s just that I’ve been suffering for about 2 months so that the plugin works on my jenkins.
Tell me where to write to another place ??
In jira jenkins, unfortunately I can not write (

**Comment by nrayapati** [comment]
Let me plan to release it soon like may be in couple of days, but if you would like to test the latest snapshot, you can download it from this job https://ci.jenkins.io/job/Plugins/job/jira-steps-plugin/job/master/80/

**Comment by nrayapati** [comment]
The standard practice for all the Jenkins projects is to log a JIRA here with appropriate jira component. 

https://issues.jenkins-ci.org/browse/JENKINS-61388?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20%27jira-steps-plugin%27

**Comment by terk28041** [comment]
The standard practice for all the Jenkins projects is to log a JIRA here with appropriate jira component.

**Comment by terk28041** [comment]
Thank you very much again)) I will test and check tomorrow))). Perhaps there is another way to keep in touch with you ??)

**Comment by nrayapati** [comment]
Gitter Chat room available if you would like post any of these messages: [Gitter](https://gitter.im/jenkinsci/jira-steps-plugin?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by nrayapati** [comment]
Replaced by https://github.com/jenkinsci/jira-steps-plugin/pull/105

**Pull request closed without merging**
